### ISSUE TITLE
请问是否有计划完善本项目，做简单配置就能正常调用后端api

### ISSUE THREAD

**Issue by hywan9** [Glide-IM/Glide-IM-Web#5]

**Comment by dengzii** [comment]
原本是打算这样做的, 但是最近半年工作比较忙, 我也有点偷懒, 想是想完善, 但是进度可能会比较慢, 多个项目需要进行

这个项目的 im 部分是可以很容易和 ui 剥离出来的

**Comment by dengzii** [comment]
有任何问题都可以加我微信直接问我 [微信二维码 https://github.com/glide-im/glide-im/issues/3](https://github.com/glide-im/glide-im/issues/3)
